// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portals_Technoprolis_RPG.Database;

#nullable disable

namespace Portals_Technoprolis_RPG.Migrations
{
    [DbContext(typeof(PortalsDbContext))]
    [Migration("20240831184227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portals_Technoprolis_RPG.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDead")
                        .HasColumnType("bit");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Character");

                    b.HasDiscriminator<string>("CharacterType").HasValue("Character");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Portals_Technoprolis_RPG.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillID");

                    b.HasIndex("PlayerId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("Portals_Technoprolis_RPG.Models.Npc", b =>
                {
                    b.HasBaseType("Portals_Technoprolis_RPG.Models.Character");

                    b.Property<int>("AwardLoot")
                        .HasColumnType("int");

                    b.Property<int>("AwardXP")
                        .HasColumnType("int");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("int");

                    b.Property<int>("NpcID")
                        .HasColumnType("int");

                    b.Property<string>("NpcName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Npc");
                });

            modelBuilder.Entity("Portals_Technoprolis_RPG.Models.Player", b =>
                {
                    b.HasBaseType("Portals_Technoprolis_RPG.Models.Character");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Loot")
                        .HasColumnType("int");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("Portals_Technoprolis_RPG.Models.Skill", b =>
                {
                    b.HasOne("Portals_Technoprolis_RPG.Models.Player", null)
                        .WithMany("PlayerSkillCollection")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("Portals_Technoprolis_RPG.Models.Player", b =>
                {
                    b.Navigation("PlayerSkillCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
